# Application name
spring.application.name=shopsphere

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:shopsphere
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (to see your data in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret Key
jwt.secret=shopsphere-secret-key-for-jwt-token-generation-2024
jwt.expiration=86400000
spring.main.allow-circular-references=true
